ifdef::env-github[]
:warning-caption: :warning:
endif::[]

= `editorconfig-gradle-plugin`

https://github.com/ec4j/editorconfig-gradle-plugin/blob/master/LICENSE[image:https://img.shields.io/github/license/ec4j/editorconfig-gradle-plugin.svg[License]]
http://search.maven.org/#search%7Cga%7C1%7Corg.ec4j.maven[image:https://img.shields.io/maven-central/v/org.ec4j.maven/editorconfig-gradle-plugin.svg[Maven
Central]]
http://travis-ci.org/ec4j/editorconfig-gradle-plugin[image:https://img.shields.io/travis/ec4j/editorconfig-gradle-plugin/master.svg?logo=travis&color=white&label=Travis+CI[Travis CI build status]]
https://ci.appveyor.com/project/ppalaga/editorconfig-gradle-plugin[image:https://img.shields.io/appveyor/ci/ppalaga/editorconfig-gradle-plugin/master.svg?logo=appveyor&color=white&label=AppVeyor+Windows+CI[AppVeyor Windows CI build status]]

`editorconfig-gradle-plugin` is a Gradle plugin for checking whether project files comply with format rules
defined in `http://editorconfig.org/[.editorconfig]` files and eventually also for fixing the violations.

WARNING: `editorconfig-gradle-plugin` is new. Expect issues of all kinds and you should definitely
https://github.com/ec4j/editorconfig-gradle-plugin/issues[report] them!


== Basic usage

`editorconfig-gradle-plugin` requires Java 7+ and Gradle 3.5+.

To apply the plugin, add the following to your project:

[source,gradle]
----
plugins {
    ...
    id 'org.ec4j.editorconfig'
}
----

After that, you can check whether your source files comply with `.editorconfig` rules:

[source,shell]
----
./gradlew editorconfigCheck
----


In case any violations are detected, you may want to fix them automagically by running

[source,shell]
----
./gradlew editorconfigFormat
----

== Configuration

There is `editorconfig` extension object. Its properties are defined in the
https://github.com/ec4j/editorconfig-gradle-plugin/tree/master/src/main/java/org/ec4j/gradle/EditorconfigExtension.java[EditorconfigExtension]
class.

[source,gradle]
----
editorconfig {
   ....
}
----

== How it works

`editorconfig-gradle-plugin` is using the same libraries as its sibling `editorconfig-maven-plugin`:
`org.ec4j.maven:ec4j-lint-api` and `org.ec4j.maven:ec4j-linters`. They are designed around the Linter interface.
https://github.com/ec4j/editorconfig-maven-plugin/blob/master/ec4j-lint-api/src/main/java/org/ec4j/maven/lint/api/Linter.java[Linter]
is a processor specialized for some particular file format (such as YAML or XML) for which it can detect whether some
particular `.editorconfig` properties are satisfied and eventually propose a
https://github.com/ec4j/editorconfig-maven-plugin/blob/master/ec4j-lint-api/src/main/java/org/ec4j/maven/lint/api/Edit.java[fix] that can
be applied automatically.

.Linters available by default:
|===
|Class name |Default includes|Default excludes |Supported `.editorconfig` properties

|https://github.com/ec4j/editorconfig-maven-plugin/blob/master/ec4j-linters/src/main/java/org/ec4j/maven/linters/TextLinter.java[TextLinter]
|`pass:[**/*]`
|
|`https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#end_of_line[end_of_line]`,
`https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#trim_trailing_whitespace[trim_trailing_whitespace]`,
`https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#insert_final_newline[insert_final_newline]`

|https://github.com/ec4j/editorconfig-maven-plugin/blob/master/ec4j-linters/src/main/java/org/ec4j/maven/linters/XmlLinter.java[XmlLinter]
|`pass:[**/*.xml]`, `pass:[**/*.xsl]`
|
|`https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#indent_style[indent_style]`,
`https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#indent_size[indent_size]`
|===

Contributions of further Linters are highly welcome! Please
https://github.com/ec4j/editorconfig-maven-plugin/issues[open an issue] when you start working on something to avoid
duplicate work.

== How to build

Prerequisites:

* Java 7+

The most common build with unit tests:

[source,shell]
----
./gradlew clean build
----

On Windows:

[source,shell]
----
.\gradlew.bat clean build
----


== Misc.

* All code and contributions are under link:/LICENSE[Apache License]
* Issues and Discussions: https://github.com/ec4j/editorconfig-gradle-plugin/issues
